[package]
name = "challenger"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
challenger-lib = { path = "challenger" }

ethers = "2.0"
tokio = { version = "1", features = ["full"] }
hex-literal = "0.4.1"
env_logger = "0.11.3"
futures = "0.3.28"
eyre = "0.6.8"
log = "0.4.20"
hex = "0.4.3"
chrono = "0.4.26"
lazy_static = "1.4.0"
tokio-util = "0.7.9"
async-trait = "0.1.73"
warp = "0.3"

[dependencies]
challenger-lib.workspace = true
tokio = { workspace = true, features = ["full"] }
env_logger = { workspace = true }
log = { workspace = true }
eyre = { workspace = true }
ethers = { workspace = true }
warp = { workspace = true }

clap = { version = "4.3.21", features = ["derive", "env"] }
rpassword = "7.2.0"
