name: release-docker
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
  workflow_dispatch: {}

jobs:
  docker-image-alpine:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker meta alpine
        id: meta_alpine
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/chronicleprotocol/challenger
          flavor: |
            latest=true
            suffix=-alpine
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Docker envs
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV
      - name: Build and push (alpine)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: ${{ steps.meta_alpine.outputs.tags }}
          build-args: |
            VERSION=${{ env.VERSION }}
