name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all --check

  test:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32
        with:
          cache-on-failure: true
      - run: curl -L https://foundry.paradigm.xyz | bash
      - run: /home/runner/.config/.foundry/bin/foundryup
      - run: ls -l /home/runner/.config/.foundry/bin
      # - run: /home/runner/.config/.foundry/bin/anvil --help
      - run: /home/runner/.config/.foundry/bin/anvil --help
      - run: cargo test --workspace --all-targets --all-features
        env:
          ANVIL_BIN: /home/runner/.config/.foundry/bin/anvil
          RUSTFLAGS: -Dwarnings

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: dtolnay/rust-toolchain@e7a32da269276b4d9cb3a0343133a168355ab751
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32
        with:
          cache-on-failure: true
      - run: cargo clippy --workspace --all-targets --all-features
        env:
          RUSTFLAGS: -Dwarnings

  typos-check:
    name: TyposCheck
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: crate-ci/typos@cfe759ac8dd421e203cc293a373396fbc6fe0d4b
        with:
          config: ./typos.toml
          isolated: true
